testing

diff --git a/.github/workflows/serverless-feature-workflow.yml b/.github/workflows/serverless-feature-workflow.yml
--- a/.github/workflows/serverless-feature-workflow.yml
+++ b/.github/workflows/serverless-feature-workflow.yml
@@ -158,62 +158,122 @@ jobs:
   #     env:
   #       SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
 
-  serverless-deploy-to-prod:
-    name: "Serverless Deploy to Prod"
+  # serverless-deploy-to-prod:
+  #   name: "Serverless Deploy to Prod"
+  #   permissions:
+  #     id-token: write
+  #     contents: read
+  #   environment: prod
+  #   #needs: pytest
+  #   # needs: [serverless-deploy-to-dev]
+  #   runs-on: ubuntu-latest
+  #   # if: github.ref == 'refs/heads/main'
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #   - name: Set AWS context
+  #     uses: aws-actions/configure-aws-credentials@v4
+  #     with:
+  #       role-to-assume: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ACCESS_ROLE }}
+  #       role-session-name: GitHub_to_AWS_via_FederatedOIDC
+  #       aws-region: ${{ secrets.AWS_REGION }}
+  #       mask-aws-account-id: true
+  #   - name: Login to Amazon ECR
+  #     uses: aws-actions/amazon-ecr-login@v2
+  #     with:
+  #       mask-password: 'true'
+  #   - name: Login to Docker Hub
+  #     uses: docker/login-action@v3
+  #     with:
+  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
+  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
+  #   - name: "Docker Build and push to AWS ECR"
+  #     id: docker-push
+  #     env:
+  #       AWS_ECR: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.APP }}
+  #       DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP }}
+  #     run: |
+  #       docker_hub_latest_tag=${{ env.DOCKER_HUB_REPO }}:latest
+  #       docker pull $docker_hub_latest_tag
+  #       if [ $? -ne 0 ]; then
+  #         echo "Docker pull failed. Image not found: $docker_hub_latest_tag"
+  #         exit 1
+  #       fi
+  #       docker tag ${docker_hub_latest_tag} ${AWS_ECR}:latest
+  #       docker push ${{ env.AWS_ECR }}:latest
+
+  #   - name: Use Node.js ${{ env.NODE_VERSION }}
+  #     uses: actions/setup-node@v4
+  #     with:
+  #       node-version: ${{ env.NODE_VERSION }}
+  #   - name: serverless deploy
+  #     run: | 
+  #       npm i -g serverless@${{ env.SERVERLESS_VERSION }}
+  #       npm install && npm list -g
+  #       tag_arg="tag=latest"
+  #       echo "tag_arg"
+  #       echo ${tag_arg}
+
+  #       serverless deploy --stage prod --param=${tag_arg}
+  #     env:
+  #       SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
+
+  label-check:
     permissions:
       id-token: write
       contents: read
-    environment: prod
-    #needs: pytest
-    # needs: [serverless-deploy-to-dev]
+    name: "Teardown Serverless Cloudformation Stack"
     runs-on: ubuntu-latest
-    # if: github.ref == 'refs/heads/main'
+    outputs:
+      deployed: ${{ steps.deploy_label_check.outputs.can-deploy }}
     steps:
-    - uses: actions/checkout@v4
+    - id: deploy_label_check
+      uses: docker://agilepathway/pull-request-label-checker:latest
+      with:
+        one_of: deploy
+        repo_token: ${{ secrets.GITHUB_TOKEN }}
+    - run: |
+        if [[ ${{ steps.deploy_label_check.outputs.label_check }} == "success" ]]; then
+
+          echo "deployed=true" >> "$GITHUB_OUTPUT"
+        else
+          echo "deployed=false" >> "$GITHUB_OUTPUT"
+        fi   
+  feature-cloudformation-stack-teardown:
+    needs: [label-check]
+    permissions:
+      id-token: write
+      contents: read
+    runs-on: ubuntu-latest
+    if: ${{ needs.label-check.outputs.can_deploy }} == true
+    outputs:
+      issue_payload: ${{ steps.deploy_label_check.outputs.can-deploy }}
+    steps:
     - name: Set AWS context
       uses: aws-actions/configure-aws-credentials@v4
       with:
-        role-to-assume: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ACCESS_ROLE }}
+        role-to-assume: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ACCESS_ROLE }}
         role-session-name: GitHub_to_AWS_via_FederatedOIDC
         aws-region: ${{ secrets.AWS_REGION }}
         mask-aws-account-id: true
-    - name: Login to Amazon ECR
-      uses: aws-actions/amazon-ecr-login@v2
-      with:
-        mask-password: 'true'
-    - name: Login to Docker Hub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ secrets.DOCKERHUB_USERNAME }}
-        password: ${{ secrets.DOCKERHUB_TOKEN }}
-    - name: "Docker Build and push to AWS ECR"
-      id: docker-push
+    - name: AWS CLI v2
+      uses: imehedi/actions-awscli-v2@latest
+    - id: teardown
+      run : |
+        stack_name=${{ env.APP }}-${{ env.ENV }}
+        aws cloudformation delete-stack --stack-name $stack_name --deletion-mode FORCE_DELETE_STACK
+        echo "Review any retained resources with the status DELETE_SKIPPED"
+        payload=$(aws cloudformation list-stack-resources --stack-name ${stack_name})
+        echo "payload=$payload" >> "$GITHUB_OUTPUT"
+  raise-issue:
+    needs: [feature-cloudformation-stack-teardown]
+    permissions:
+      id-token: write
+      issues: write
+      contents: read
+    runs-on: ubuntu-latest
+    if: ${{ needs.feature-cloudformation-stack-teardown.outputs.payload }} != ""
+    steps:
+    - uses: actions/checkout@v3
+    - uses: JasonEtco/create-an-issue@v2
       env:
-        AWS_ECR: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.APP }}
-        DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP }}
-      run: |
-        docker_hub_latest_tag=${{ env.DOCKER_HUB_REPO }}:latest
-        docker pull $docker_hub_latest_tag
-        if [ $? -ne 0 ]; then
-          echo "Docker pull failed. Image not found: $docker_hub_latest_tag"
-          exit 1
-        fi
-        docker tag ${docker_hub_latest_tag} ${AWS_ECR}:latest
-        docker push ${{ env.AWS_ECR }}:latest
-
-    - name: Use Node.js ${{ env.NODE_VERSION }}
-      uses: actions/setup-node@v4
-      with:
-        node-version: ${{ env.NODE_VERSION }}
-    - name: serverless deploy
-      run: | 
-        npm i -g serverless@${{ env.SERVERLESS_VERSION }}
-        npm install && npm list -g
-        tag_arg="tag=latest"
-        echo "tag_arg"
-        echo ${tag_arg}
-
-        serverless deploy --stage prod --param=${tag_arg}
-      env:
-        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
-
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
