testing

diff --git a/.github/workflows/serverless-feature-workflow.yml b/.github/workflows/serverless-feature-workflow.yml
--- a/.github/workflows/serverless-feature-workflow.yml
+++ b/.github/workflows/serverless-feature-workflow.yml
@@ -73,6 +73,7 @@ jobs:
     permissions:
       id-token: write
       contents: read
+      deployments: write
     runs-on: ubuntu-latest
     environment: feature
     steps:
@@ -92,19 +93,28 @@ jobs:
       with:
         stack-name: ${{ env.APP }}-feature
         region: ${{ secrets.AWS_REGION }}
-    - id: set_deployment_as_inactive
+    - name: Install jq
       run: |
         sudo apt-get update
         sudo apt-get install -y jq
+    - id: set_deployment_as_inactive
+      run: |
         DEPLOYMENT_ID=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github+json" \
           "https://api.github.com/repos/KremzeeqOrg/fruit-project-api-scraper/deployments?environment=feature" | \
           jq -r 'sort_by(.created_at) | last | .id')
         echo "Latest deployment ID: $DEPLOYMENT_ID"
-        curl -L \
+        HTTP_STATUS=$(curl -L \
+          -o /dev/null \
+          -w "%{http_code}" \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/KremzeeqOrg/fruit-project-api-scraper/deployments/$DEPLOYMENT_ID/statuses \
-          -d '{"environment":"feature","state":"inactive","description":"Deployment finished successfully."}'
+          -d '{"environment":"feature","state":"inactive","description":"Deployment finished successfully."}')
+        echo "HTTP status code: $HTTP_STATUS"
+        if [[ "$HTTP_STATUS" == "400" || "$HTTP_STATUS" == "403" ]]; then
+          echo "Failed with status code $HTTP_STATUS"
+          exit 1
+        fi
