refactor

diff --git a/.github/workflows/serverless-main-workflow.yml b/.github/workflows/serverless-main-workflow.yml
--- a/.github/workflows/serverless-main-workflow.yml
+++ b/.github/workflows/serverless-main-workflow.yml
@@ -5,10 +5,9 @@ on:
 env:
   TEST_DIR: "src/tests"
   NODE_VERSION: 20
-  PYTHON_VERSION: '3.10'
+  PYTHON_VERSION: 3.10
   SERVERLESS_VERSION: 3.38.0
   APP: "fruit-project-api-scraper"
-
 
 jobs:
   pytest:
@@ -34,22 +33,24 @@ jobs:
     - name: Test with pytest
       run: pytest -vv ${{ env.TEST_DIR }}/test_${{ matrix.test_file }}.py
       
+
   serverless-deploy-to-dev:
+    name: "Serverless Deploy to Dev"
     permissions:
       id-token: write
       contents: read
-    name: "Serverless Deploy to Dev"
-    needs: pytest
+    environment: dev
+    needs: [pytest]
     runs-on: ubuntu-latest
-    if: github.ref == 'refs/heads/main'
+    # if: github.ref == 'refs/heads/main'
     steps:
     - uses: actions/checkout@v4
     - name: Set AWS context
       uses: aws-actions/configure-aws-credentials@v4
       with:
-        role-to-assume: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE }}
+        role-to-assume: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ACCESS_ROLE }}
         role-session-name: GitHub_to_AWS_via_FederatedOIDC
-        aws-region: ${{ env.AWS_REGION }}
+        aws-region: ${{ secrets.AWS_REGION }}
         mask-aws-account-id: true
     - name: Login to Amazon ECR
       uses: aws-actions/amazon-ecr-login@v2
@@ -63,19 +64,17 @@ jobs:
     - name: "Docker Build and push to AWS ECR"
       id: docker-push
       env:
-        AWS_ECR: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
+        AWS_ECR: ${{ secrets.FRUIT_PROJECT_DEV_AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.APP }}
       run: |
         sha_short=$(git rev-parse --short HEAD)
-        "image_sha_tag=develop-${sha_short}" >> $GITHUB_OUTPUT
-        tag=${{ env.AWS_ECR }}/${image_sha_tag}
+        image_sha_tag=develop-${sha_short}
+        echo "image_sha_tag=${image_sha_tag}" >> $GITHUB_OUTPUT
+        aws_tag=${{ env.AWS_ECR }}:${image_sha_tag}
+        docker_hub_tag=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP }}:latest
 
-        docker build --platform linux/amd64 -t ${tag} .
-        docker push ${{ env.AWS_ECR }}/${{ env.APP }} --all-tags
-        id=$(docker images -q ${tag})
-        latest_tag=${{ env.APP }}:latest
-        docker_hub_latest_tag=${{ secrets.DOCKERHUB_USERNAME }}/${latest_tag}
-        docker ${id} tag ${latest_tag $docker_hub_latest_tag}
-        docker push ${docker_hub_latest_tag}
+        docker build --platform linux/amd64 -t ${aws_tag} -t ${docker_hub_tag} .
+        docker push ${aws_tag}
+        docker push ${docker_hub_tag}
 
     - name: Use Node.js ${{ env.NODE_VERSION }}
       uses: actions/setup-node@v4
@@ -87,5 +86,64 @@ jobs:
         npm install && npm list -g
         tag_arg="tag=${{ steps.docker-push.outputs.image_sha_tag }}"
         serverless deploy --stage dev --param=${tag_arg}
+      env:
+        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
+
+  serverless-deploy-to-prod:
+    name: "Serverless Deploy to Prod"
+    permissions:
+      id-token: write
+      contents: read
+    environment: prod
+    #needs: pytest
+    needs: [serverless-deploy-to-dev]
+    runs-on: ubuntu-latest
+    # if: github.ref == 'refs/heads/main'
+    steps:
+    - uses: actions/checkout@v4
+    - name: Set AWS context
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        role-to-assume: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ACCESS_ROLE }}
+        role-session-name: GitHub_to_AWS_via_FederatedOIDC
+        aws-region: ${{ secrets.AWS_REGION }}
+        mask-aws-account-id: true
+    - name: Login to Amazon ECR
+      uses: aws-actions/amazon-ecr-login@v2
+      with:
+        mask-password: 'true'
+    - name: Login to Docker Hub
+      uses: docker/login-action@v3
+      with:
+        username: ${{ secrets.DOCKERHUB_USERNAME }}
+        password: ${{ secrets.DOCKERHUB_TOKEN }}
+    - name: "Docker Build and push to AWS ECR"
+      id: docker-push
+      env:
+        AWS_ECR: ${{ secrets.FRUIT_PROJECT_PROD_AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.APP }}
+        DOCKER_HUB_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.APP }}
+      run: |
+        docker_hub_latest_tag=${{ env.DOCKER_HUB_REPO }}:latest
+        docker pull $docker_hub_latest_tag
+        if [ $? -ne 0 ]; then
+          echo "Docker pull failed. Image not found: ${docker_hub_latest_tag}"
+          exit 1
+        fi
+        docker tag ${docker_hub_latest_tag} ${AWS_ECR}:latest
+        docker push ${{ env.AWS_ECR }}:latest
+
+    - name: Use Node.js ${{ env.NODE_VERSION }}
+      uses: actions/setup-node@v4
+      with:
+        node-version: ${{ env.NODE_VERSION }}
+    - name: serverless deploy
+      run: | 
+        npm i -g serverless@${{ env.SERVERLESS_VERSION }}
+        npm install && npm list -g
+        tag_arg="tag=latest"
+        echo "tag_arg"
+        echo ${tag_arg}
+
+        serverless deploy --stage prod --param=${tag_arg}
       env:
         SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
